### ISSUE TITLE
An idea for basic modeling

### ISSUE THREAD

**Issue by rethissunstar** [cherah-petra/NeighbourhoodLibrary#7]
Keegan, Cheryl and kevin suggested that we follow the model of the last mini-project per Ali's recommendations.

**Comment by Keegan-Omel** [comment]
This ended up working well for the group, we were able to get to a solid starting point and create a starting point for the project. Everyone was able to pull after the inital commit and have the same starting point for the project.

**Comment by rethissunstar** [comment]
had thought about working from a blank using the model and replicating as we need.  the Team was very convincing that was not the path
